#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

script:
  - npm run build.prod

deploy:
  - provider: s3
    access_key_id: AKIAJQNIWDDLDQQ4TSQQ
    secret_access_key:
      secure: "VTWlmsKxxg4Qc6FEsgqzmTUzOEv0CR/8op0lerc1d5XhyovWvosQN6V7GMEt0jZcOxKboVmBNO9WsmUtcdx4l64xbmLyVnfcL7tHq7w4s3Uhcjlunib6pexcHwwT8M1fmygi0tn8IA22EAuFLG/iOS8dkg6b2UGoJK8TjNBgDBL4W7Z55KBN7leMOlenZSfiU+OTdMOYtMKd5YFXWMztZwE/VOPS0o52R+7UmKWpcaR1ZIkTH7Qoq+GKQbdrnFiQBaYylx+Eundfil4fGvxPJcQOHEQebaSBwRkfmBtL9DBmt4JhkMI0N4L7gmd6E9Tx8xR3Q7dP/VIHY9Ct2uX2dNqvENiztSTaSIQjugdK2SApOBeDxckcnZ/XK3TbfQqFJwGvTpridtuxe9/hzOqQABa6XEZ7KNCBtj5ZIiA4lap9lYwmdgMwER1zqJmWrnigdWlDn8m4u+zHhOd2d87odaHovqLOMCM/Stu47G5/q/6xCoOSZREPHGxeYqTKu+TT+4TbfdSrsoENWUl5oN7O/0fVQzfdhqHibXziDbwsXUGPs3EG0soxU1hlrhwNebzEEmxWeJY03zOleH+PRWqkUr7lo1jt3feGVAKlkW0/qc6PbDy5Pc7JdkZybx0S7UQKJMg+1e+P1cDT92t6KLMa5tPuV8bF0OcFvRwI1DnBONE="
    bucket: stockyard-app
    skip_cleanup: true
    local_dir: dist/prod
    on:
      branch: master

notifications:
  email:
    on_failure: change
    on_success: change
