#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

script:
  - npm run build.prod

deploy:
  - provider: s3
    access_key_id: AKIAJQNIWDDLDQQ4TSQQ
    secret_access_key:
      secure: "xpViTX+q+4Y0QjSl+7RGTDQn9ODrfZZYBg4kTlNQ1MkKHCDSDS8gUtzwTGpgRaxt9UqLP23VRgLr8s/vlF/On/qZRsD7xGHK2qEEdWZ9NbPmWnaTJcJUCt9km7OKPXC/y6AZ2KdrN6bysLhHsX1Z8vd6f2qHQArg3Q64aC+5qxDxde21odCfCo03qS4NPTfgqkp03rrmcbU4C/z8uIEkajGbo09PnRxGMgOQVxZi3y3wGyCTYjgYEYb2jcaf/Bh7gkIK2PwzER/+OLMQdPGPk+QXJhev5bWLuV9FMFoHYNoxu9OKlXpCea53t8giy6VW3VJ5dtYlMr7V8PWoiNCfQ3RtPZdOmuU1FWHyyi2JzdVcS10VCBeOB1G5fHcRgRkFebinSoaq57f4tvV+puqGLN7O+TbEI1XBbXHfIfB3MoZ8Um7JiP/+gp+GgOuD5fFjQf0RhOLdr0kjeQVvpg0LQ8RDE/Vk1yJ0GPxRYnu3jU2wxWvW4GI+CWhhLLhd4o62PtvS3WOk58cBZiJDEZvUMQivzX9l2kHoyIUQaVzKtD+JYIKoFEnBug8wd72V9Gmeruf0U+OCNjIVH6l9ghvdciCKMpjkmfeJKtMJCxEIHJwrvFo885eyHsB7tBI7hqNXdfKo+JC9g/BQdS8dplWSyn9nkkDuCBeMtTHjXcvZsE8="
    bucket: stockyard-app
    skip_cleanup: true
    local_dir: dist/prod
    on:
      branch: master

notifications:
  email:
    on_failure: change
    on_success: change
